name: Auto-Merge Dependabot PRs

on:
  pull_request_target:
# default read-only permission
permissions:
  contents: read

jobs:
  auto-merge:
    permissions:
      contents: write  # ahmadnassri/action-dependabot-auto-merge
      pull-requests: write  # ahmadnassri/action-dependabot-auto-merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if PR should be auto-merged
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          # This must be a personal access token with push access
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # By default, squash and merge, so Github chooses nice commit messages
          command: squash and merge
