name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  check_suite:
    types: [completed]
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Auto merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          command: 'merge'
          target: 'minor'
